### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by SohamJa1n** [Zorpal/NEA#1]
What are the instructions for compiling?

**Comment by Zorpal** [comment]
Pull the repo into vscode, cd into the folder you have cloned the project into, should have the .venv folder in.
On a zsh macOS terminal, use:

source .venv/bin/activate

On powershell, use:
.venv\Scripts\Activate.ps1

Use a split terminal, cd to NEA (django backend server) on one terminal and cd into frontend on the other terminal

Within the NEA directory, use:
python manage.py runserver

Within the frontend directory, use:
npm run dev

**Comment by Zorpal** [comment]
FYI still in the process of updating my project so some bugs are still present on this commit as well as missing features

**Comment by Kev360** [comment]
![image](https://github.com/user-attachments/assets/39b07b98-0042-4b99-812b-a2ccc8c6de12)

**Comment by Zorpal** [comment]
Apologies, I have updated my repo without the .venv folder as it is quite large, I will post instructions on a readme.
